/** 
 * \file fw100-ril-timer.c 
 * \brief ril timed based processing
 *
 */

#include <assert.h>
#include <ctype.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include <alloca.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <getopt.h>
#include <pthread.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <termios.h>
#include <unistd.h>

#include <cutils/properties.h>
#include <cutils/sockets.h>
#include <telephony/ril.h>

#include <atchannel.h>
#include <at_tok.h>
#include <misc.h>

#define LOG_TAG "RIL"
#include <utils/Log.h>

#include <fw100-ril.h>
#include <rilinfo.h>

// build options
#define BUILD_DEBUG_1	0

static char pollSavedCREG[64];
static char pollSavedCSQ[64];

/**
 * \brief get registration state
 * 
 * fw100
 * at+CREG?                                                                        
 * +CREG:1,4145,7,1     
 * 
 * enfora
 * at+CREG?
 * +CREG: 2,1,0080,D23E
 * 
 * RIL_UNSOL_RESPONSE_NETWORK_STATE_CHANGED
 *
 * Called when network state, operator name, or GPRS state has changed
 * Basically on, +CREG and +CGREG
 *
 * Callee will invoke the following requests on main thread:
 *
 * RIL_REQUEST_REGISTRATION_STATE
 * RIL_REQUEST_GPRS_REGISTRATION_STATE
 * RIL_REQUEST_OPERATOR
 *
 * "data" is NULL
 */ 
void pollNetworkRegistration()
{
    int err;
    int max;
    char *line;
    ATResponse *p_response = NULL;

    // Get registration state
    err = at_send_command_singleline ("AT+CREG?", "+CREG:", &p_response);
    if((err != 0) || (p_response->success == 0))
    {
        goto error;
    }

    line = p_response->p_intermediates->line;

    // if no change in CREG then return
    max = (strlen(line) > sizeof(pollSavedCREG)) ? sizeof(pollSavedCREG) : strlen(line);
    if (!strncmp(pollSavedCREG, line, max))
      return;

    // save a copy 
    strncpy(pollSavedCREG, line, sizeof(pollSavedCREG));

    #if BUILD_DEBUG_1
    LOGD("%s pollSavedCREG=%s", __FUNCTION__, pollSavedCREG);
    #endif

    // notification but no data is in notification.
    // Phone app makes sync RIL request calls when notified.
    RIL_onUnsolicitedResponse (RIL_UNSOL_RESPONSE_NETWORK_STATE_CHANGED, NULL, 0);

    if (NULL != p_response) at_response_free(p_response);
    return;

error:
    if (NULL != p_response) at_response_free(p_response);
}

/**
 * \brief get signal strength
 * 
 * response is defined by the following structure whose
 * binary fields comprise an array of 7 integers.
 * since this is only used in local UNIX domain, 
 * structure pack/pad and byte order are native
 * as generated by compiler.
 * 
 * GW:   0,1
 * CDMA: 2,3
 * EVDO  4,5,6
 *
 * typedef struct {
 * RIL_GW_SignalStrength   GW_SignalStrength;
 * RIL_CDMA_SignalStrength CDMA_SignalStrength;
 * RIL_EVDO_SignalStrength EVDO_SignalStrength;
 * } RIL_SignalStrength;
 * 
 * n.b. see fw100-ril-rqst.c requestSignalStrengthEVDO 
 * for EVDO aware version of this function.
 */
static void pollSignalStrength()
{
    int max;
    int err;
    int notify[7];
    char *line;
    ATResponse *p_response = NULL;

    memset(notify, 0, sizeof(notify));

    err = at_send_command_singleline("AT+CSQ", "+CSQ:", &p_response);
    if (err < 0 || p_response->success == 0) {
        goto error;
    }

    line = p_response->p_intermediates->line;

    // if no change in CSQ then return
    max = (strlen(line) > sizeof(pollSavedCSQ)) ? sizeof(pollSavedCSQ) : strlen(line);
    if (!strncmp(pollSavedCSQ, line, max))
      return;

    // save a copy 
    strncpy(pollSavedCSQ, line, sizeof(pollSavedCSQ));

    #if BUILD_DEBUG_1
    LOGD("%s pollSavedCSQ=%s", __FUNCTION__, pollSavedCSQ);
    #endif

    err = at_tok_start(&line);
    if (err < 0) goto error;

    err = at_tok_nextint(&line, &(notify[0]));
    if (err < 0) goto error;

    err = at_tok_nextint(&line, &(notify[1]));
    if (err < 0) goto error;

    RIL_onUnsolicitedResponse ( RIL_UNSOL_SIGNAL_STRENGTH,
      notify, sizeof(notify));

    if (NULL != p_response) at_response_free(p_response);
    return;

error:
    if (NULL != p_response) at_response_free(p_response);
}

/**
 * \brief process polled modem state: 
 * CREG 
 * CSQ
 * 
 * if auto ppp is enabled start and monitor it
 */
void fw100ModemTimer()
{
    fw100SessionCtx_t *ctx = fw100GetSessionCtx();

    pollSignalStrength();

    pollNetworkRegistration();

#if GPS_TEST_NMEA
	// output test strings at this modem timer rate nominal every 10 seconds
	#define GPS_TEST_GPGLL "$GPGLL,3307.055350,N,11718.467958,W,234014.000,A,A*45"
	#define GPS_TEST_GPGSA "$GPGSA,A,3,22,03,19,09,,,,,,,,,2.55,2.37,0.94*09"
        if (ctx->gpsFifoEnable) rilWriteGPSFifo(ctx, RIL_GPS_FIFOPATH, GPS_TEST_GPGLL);
        if (ctx->gpsTtyEnable)  rilWriteGPSTty(ctx, GPS_TEST_GPGSA, 0);
#endif

#if 0
    #if BUILD_DEBUG_1
    LOGD("%s dataCallIsAuto=%d", __FUNCTION__, ctx->dataCallIsAutomatic);
    #endif
    if ((ctx->dataCallIsAutomatic) && (ctx->moduleIsActivated))
    {
      pppAutomatic();
    }
#endif

}


