/**
 * \file rilinfo.c 
 * \brief vendor ril request and status profiles
 *
 *  \if license
 *  Copyright (c) 2011 Cypherbridge Systems, LLC.
 *  www.cypherbridge.com
 *  info@cypherbridge.com
 *  \endif
 *
 */

#include <stdlib.h>
#include <string.h>

#include <telephony/ril.h>
#include <rilinfo.h>

/**
 * \brief ril request info table
 * table is sparse 
 */
static ril_request_info_t ril_request_info [] = 
{
	 {RIL_REQUEST_GET_SIM_STATUS,            RRI_PROFILE_NS, "RIL_REQUEST_GET_SIM_STATUS"},
         {RIL_REQUEST_GET_CURRENT_CALLS,         RRI_PROFILE_1,  "RIL_REQUEST_GET_CURRENT_CALLS"},
         {RIL_REQUEST_DIAL,                      RRI_PROFILE_NS,  "RIL_REQUEST_DIAL"},
         {RIL_REQUEST_SCREEN_STATE,              RRI_PROFILE_1,  "RIL_REQUEST_SCREEN_STATE"}, 
         {RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE, RRI_PROFILE_2, "RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE"},
         {RIL_REQUEST_SET_MUTE,                  RRI_PROFILE_2,  "RIL_REQUEST_SET_MUTE"},
         {RIL_REQUEST_CDMA_FLASH,                RRI_PROFILE_1,  "RIL_REQUEST_CDMA_FLASH"},
         {RIL_REQUEST_HANGUP,                    RRI_PROFILE_NS,  "RIL_REQUEST_HANGUP"},
         {RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND, RRI_PROFILE_1, "RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND"},
         {RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND, RRI_PROFILE_1, "RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND"},
         {RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE, RRI_PROFILE_1, "RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE"},
         {RIL_REQUEST_ANSWER,                    RRI_PROFILE_1,  "RIL_REQUEST_ANSWER"},
         {RIL_REQUEST_CONFERENCE,                RRI_PROFILE_2,  "RIL_REQUEST_CONFERENCE"},
         {RIL_REQUEST_UDUB,                      RRI_PROFILE_1,  "RIL_REQUEST_UDUB"},
         {RIL_REQUEST_SEPARATE_CONNECTION,       RRI_PROFILE_1,  "RIL_REQUEST_SEPARATE_CONNECTION"},
         {RIL_REQUEST_SIGNAL_STRENGTH,           RRI_PROFILE_1,  "RIL_REQUEST_SIGNAL_STRENGTH"},
         {RIL_REQUEST_REGISTRATION_STATE,        RRI_PROFILE_1,  "RIL_REQUEST_REGISTRATION_STATE"},
         {RIL_REQUEST_GPRS_REGISTRATION_STATE,   RRI_PROFILE_1,  "RIL_REQUEST_GPRS_REGISTRATION_STATE"},
         {RIL_REQUEST_OPERATOR,                  RRI_PROFILE_1,  "RIL_REQUEST_OPERATOR"},
         {RIL_REQUEST_CDMA_SUBSCRIPTION,         RRI_PROFILE_1,  "RIL_REQUEST_CDMA_SUBSCRIPTION"},
         {RIL_REQUEST_DEVICE_IDENTITY,           RRI_PROFILE_1,  "RIL_REQUEST_DEVICE_IDENTITY"},
         {RIL_REQUEST_RADIO_POWER,               RRI_PROFILE_1,  "RIL_REQUEST_RADIO_POWER"},
         {RIL_REQUEST_QUERY_FACILITY_LOCK,       RRI_PROFILE_1,  "RIL_REQUEST_QUERY_FACILITY_LOCK"},
         {RIL_REQUEST_SET_FACILITY_LOCK,         RRI_PROFILE_1,  "RIL_REQUEST_SET_FACILITY_LOCK"},
         {RIL_REQUEST_DTMF,                      RRI_PROFILE_NS, "RIL_REQUEST_DTMF"}, 
         {RIL_REQUEST_DTMF_START,                RRI_PROFILE_NS, "RIL_REQUEST_DTMF_START"},
         {RIL_REQUEST_DTMF_STOP,                 RRI_PROFILE_NS, "RIL_REQUEST_DTMF_STOP"},
         {RIL_REQUEST_CDMA_BURST_DTMF,           RRI_PROFILE_NS, "RIL_REQUEST_CDMA_BURST_DTMF"},
         {RIL_REQUEST_SEND_SMS,                  RRI_PROFILE_NS, "RIL_REQUEST_SEND_SMS"},
         {RIL_REQUEST_SETUP_DATA_CALL,           RRI_PROFILE_1,  "RIL_REQUEST_SETUP_DATA_CALL"},
         {RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE, RRI_PROFILE_1,  "RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE"},
         {RIL_REQUEST_DEACTIVATE_DATA_CALL,      RRI_PROFILE_1,  "RIL_REQUEST_DEACTIVATE_DATA_CALL"},
         {RIL_REQUEST_SMS_ACKNOWLEDGE,           RRI_PROFILE_1,  "RIL_REQUEST_SMS_ACKNOWLEDGE"},
         {RIL_REQUEST_GET_IMSI,                  RRI_PROFILE_1,  "RIL_REQUEST_GET_IMSI"},
         {RIL_REQUEST_BASEBAND_VERSION,          RRI_PROFILE_1,  "RIL_REQUEST_BASEBAND_VERSION"},
         {RIL_REQUEST_GET_IMEI,                  RRI_PROFILE_1,  "RIL_REQUEST_GET_IMEI"},
         {RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE, RRI_PROFILE_1, "RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE"},
         {RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE, RRI_PROFILE_1, "RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE"},
         {RIL_REQUEST_SIM_IO,                    RRI_PROFILE_NS, "RIL_REQUEST_SIM_IO"},
         {RIL_REQUEST_SEND_USSD,                 RRI_PROFILE_1,  "RIL_REQUEST_SEND_USSD"},
         {RIL_REQUEST_CANCEL_USSD,               RRI_PROFILE_1,  "RIL_REQUEST_CANCEL_USSD"},

         {RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE, RRI_PROFILE_1, "RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE"},
         {RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC, RRI_PROFILE_1, "RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC"},
         {RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL,  RRI_PROFILE_1,  "RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL"},
         {RIL_REQUEST_QUERY_AVAILABLE_NETWORKS,  RRI_PROFILE_1,  "RIL_REQUEST_QUERY_AVAILABLE_NETWORKS"},

         {RIL_REQUEST_DATA_CALL_LIST,            RRI_PROFILE_1,  "RIL_REQUEST_DATA_CALL_LIST"},
         {RIL_REQUEST_OEM_HOOK_RAW,              RRI_PROFILE_NS, "RIL_REQUEST_OEM_HOOK_RAW"},
         {RIL_REQUEST_OEM_HOOK_STRINGS,          RRI_PROFILE_NS, "RIL_REQUEST_OEM_HOOK_STRINGS"},
         {RIL_REQUEST_WRITE_SMS_TO_SIM,          RRI_PROFILE_NS, "RIL_REQUEST_WRITE_SMS_TO_SIM"},
         {RIL_REQUEST_DELETE_SMS_ON_SIM,         RRI_PROFILE_NS, "RIL_REQUEST_DELETE_SMS_ON_SIM"},
         {RIL_REQUEST_ENTER_SIM_PIN,             RRI_PROFILE_NS, "RIL_REQUEST_ENTER_SIM_PIN"},
         {RIL_REQUEST_ENTER_SIM_PIN2,            RRI_PROFILE_NS, "RIL_REQUEST_ENTER_SIM_PIN2"},
         {RIL_REQUEST_ENTER_SIM_PUK2,            RRI_PROFILE_NS, "RIL_REQUEST_ENTER_SIM_PUK2"},
         {RIL_REQUEST_CHANGE_SIM_PIN,            RRI_PROFILE_NS, "RIL_REQUEST_CHANGE_SIM_PIN"},
         {RIL_REQUEST_CHANGE_SIM_PIN2,           RRI_PROFILE_NS, "RIL_REQUEST_CHANGE_SIM_PIN2"},
         {RIL_REQUEST_ENTER_SIM_PUK,             RRI_PROFILE_NS, "RIL_REQUEST_ENTER_SIM_PUK"},
         {RIL_REQUEST_CDMA_SEND_SMS,             RRI_PROFILE_1,  "RIL_REQUEST_CDMA_SEND_SMS"},
         {RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM,    RRI_PROFILE_NS, "RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM"},
         {RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM,   RRI_PROFILE_NS, "RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM"},
         {RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE,      RRI_PROFILE_1,  "RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE"},
         {RIL_REQUEST_STK_SET_PROFILE,           RRI_PROFILE_NS, "RIL_REQUEST_STK_SET_PROFILE"},
         {RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND, RRI_PROFILE_NS, "RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND"},
         {RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE,RRI_PROFILE_NS, "RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE"},
         {RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE, RRI_PROFILE_2, "RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE"},
         {RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE, RRI_PROFILE_2, "RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE"},
	 {0, 0, ""}
};

/**
 *  \brief linear search for request ID, returning name
 *
 *  \param request - enumerated RIL request ID
 *  \return request name string, or NULL on search fail
 */ 
const char *requestToString(int request)
{
	ril_request_info_t *info = ril_request_info;
	do 
	{
		if (request == info->id) 
			return info->name;
		info++;

	} while (info->id != 0);

	return NULL;
}

/**
 *  \brief linear search for request ID, returning descriptor
 *
 *  \param request - enumerated RIL request ID
 *  \return pointer to request info structure, or NULL on search fail
 */ 
const ril_request_info_t *requestInfo(int request)
{
	ril_request_info_t *info = ril_request_info;
	do 
	{
		if (request == info->id) 
			return info;
		info++;

	} while (info->id != 0);

	return NULL;
}

